# Site Settings
title: Centifyy's Website
description: A personal portfolio to showcase my personal creations
author: Maaz
email: maazarshadakhund123@gmail.com

# Build Settings
theme: jekyll-theme-minimal # This applies a clean, simple default theme

